### PR TITLE
Update readme to new rspec syntax

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
This would also signal to potential users it works for newer Rspec
versions.

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
It seems like Travis isn't triggered, that might need an update too 😄

**Comment by pcreux** [comment]
This is great for marketing indeed! Thanks a lot!

**Comment by ZJvandeWeg** [comment]
@pcreux The build failure seems unrelated, versions aren't locked. What do you think about bumping rake and rspec?

**Comment by pcreux** [comment]
That would make a lot of sense. I don't have much time this week, feel free
to give it a shot! 😉

**Pull request closed without merging**
